# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_auth', '0011_auto_20171109_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
